name: Sync with Gitee

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜（UTC时间）运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with Gitee
      run: |
        git remote add gitee https://NEUcmk:13cf274fc9bdb59dbee705f3a8fd4bd1@gitee.com/NEUcmk/glados-checkin.git
        git push --force gitee main
